export const WILDCARD_ROUTES = {
  PRIVATE: '/not-found',
  PUBLIC: '/not-found',
};
export const ROUTES = {
  HOMEPAGE: '/',
  USERS: '/users',
  LOGIN: '/login',
  REGISTER: '/register',
  VERIFY_EMAIL: '/verify-email',
  FORGOT_PASSWORD: '/forgot/password',
  RESET_PASSWORD: '/auth/reset-password/:token',
  ABOUT: '/about-us',
  WINNERS: '/winners',
  WINNERS_STATS: '/contract/stats',
  TOKEN_MANAGEMENT: '/contract/token-management',
  LOTTERY_MANAGEMENT: '/contract/lottery-management',
  WINNERS_LIST: '/winners/list',
  CONTENT_MANAGEMENT: '/content-management',
  TOP_NAVBAR_CONTENT: '/content-management/top-navbar-content',
  VIDEO_CONTENT: '/content-management/video-content',
  PRIZE_SECTION_CONTENT: '/content-management/prize-section-content',
  WINNER_LIST_CONTENT: '/content-management/winner-list-content',
  WINNER_RULES_CONTENT: '/content-management/winner-rules-content',
  CONTRACT_DETAILS_CONTENT: '/content-management/contract-details-content',
  ROAD_MAP_SECTION_CONTENT: '/content-management/roadmap-section-content',
  FEATURES_CONTENT: '/content-management/features-content',
  TOKEN_INFORMATION_CONTENT: '/content-management/token-information-content',
  PREMIUM_MARKET_PLACE_CONTENT:
    '/content-management/premium-marketplace-content',
  PREMIUM_TOKEN_WALLET_CONTENT:
    '/content-management/premium-token-wallet-content',
  TOKEN_STATS_INFORMATION_CONTENT:
    '/content-management/token-stats-info-content',
  EXTERNAL_AUDIT_CONTENT: '/content-management/external-audit-content',
  TOKEN_SUPPLY_CONTENT: '/content-management/token-supply-content',
  JOIN_AIRDROP_CONTENT: '/content-management/join-airdrop-content',
  PARTNER_CONTENT: '/content-management/partners-content',
  FOOTER_CONTENT: '/content-management/footer-content',
  AIR_DROP: '/air-drop',
  AIR_DROP_LIST: '/air-drop/list',
  AIR_DROP_HISTORY: '/air-drop/history',
  PRIZE_SECTION_POPUP_CONTENT: '/prize-section/pop-up-content',
  PRIVACY_POLICY_PAGE_CONTENT: '/pages/privacy-policy-page-content',
  TERM_AND_CONDITION_PAGE_CONTENT: '/pages/term-and-condition-page-content',
  META_CONTENT: '/pages/meta-content',
  CHANGE_PASSWORD: '/change-password',
  MANUAL_TRANSFER: '/manual-transfer',
  MANUAL_TRANSFER_LIST: '/manual-transfer/manual-transfer-list',
};
